Sends captions through the stream
EnvelopSound/obs-studio pull request #1
Opened 2021-06-14 16:04 UTC by RuiOrey

Also fixes some windows compilation problems
code adapted from branch `cea-608-json`

2021-06-14 17:08 UTC, roddylindsay commented on plugins/CMakeLists.txt
> +#	add_subdirectory(obs-vst3)
does this impact non-win?

2021-06-14 17:08 UTC, roddylindsay commented on libobs/obs-output.c
> +		double duration = 0.033;
is this the only change from the branch that I created before?

2021-06-14 21:58 UTC, roddylindsay requested changes

2021-06-14 21:58 UTC, roddylindsay commented on libobs/obs-encoder.c
> +	blog(LOG_INFO, "timebase_num: %d", voi->fps_den);
remove

2021-06-14 21:58 UTC, roddylindsay commented on libobs/obs-internal.h
> +/* ref-counting	 */
revert

2021-06-17 20:39 UTC, RuiOrey commented
removed the logs and wrong spacing on https://github.com/EnvelopSound/obs-studio/pull/1#discussion_r651305885

2021-06-19 20:38 UTC, merged